name = "IMinuit"
uuid = "beb75e20-2205-47e6-ad51-640e9c2309f1"
authors = ["Feng-Kun Guo"]
version = "0.1.1"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PyCall = ">=1"
Plots = ">=1"
julia = ">=1.2"
DataFrames = ">=0.21"
Combinatorics = ">=1"
ForwardDiff = ">=0.10"
StatsBase = ">=0.30"
